# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options="-Xmx2048m"

# Point Gradle to your Android Studio's stable Java 21
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr

# Performance Boosters
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true

# Android Standard Settings
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true